// <auto-generated />
using System;
using MercuryGo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercuryGo.Api.Migrations
{
    [DbContext(typeof(MercuryGoDbContext))]
    [Migration("20260830205553_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Aceites, azúcares y productos secos",
                            Nombre = "Almacén y Comestibles"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Harinas, fideos y sémolas",
                            Nombre = "Harinas y Pastas"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Yerba mate, té y café",
                            Nombre = "Infusiones"
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Caja x 12 unidades",
                            Disponible = true,
                            Nombre = "Aceite de Girasol 1.5L",
                            Precio = 2400.00m
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CategoriaId = 2L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Pack x 10 unidades",
                            Disponible = true,
                            Nombre = "Harina 000 1kg",
                            Precio = 950.00m
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Bolsa x 10 unidades",
                            Disponible = false,
                            Nombre = "Arroz Largo Fino 1kg",
                            Precio = 1800.00m
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            CategoriaId = 2L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Caja x 20 paquetes",
                            Disponible = true,
                            Nombre = "Fideos Guiseros 500g",
                            Precio = 1100.00m
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Fardo x 10 unidades",
                            Disponible = true,
                            Nombre = "Azúcar Común 1kg",
                            Precio = 1250.00m
                        },
                        new
                        {
                            Id = 6L,
                            Activo = true,
                            CategoriaId = 3L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Pack x 6 unidades",
                            Disponible = true,
                            Nombre = "Yerba Mate 1kg",
                            Precio = 3400.00m
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Producto", b =>
                {
                    b.HasOne("MercuryGo.Api.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
