// <auto-generated />
using System;
using MercuryGo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercuryGo.Api.Migrations
{
    [DbContext(typeof(MercuryGoDbContext))]
    [Migration("20260830210215_ClientesPedidos")]
    partial class ClientesPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Aceites, azúcares y productos secos",
                            Nombre = "Almacén y Comestibles"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Harinas, fideos y sémolas",
                            Nombre = "Harinas y Pastas"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Yerba mate, té y café",
                            Nombre = "Infusiones"
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("cuit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_cuit");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "30-71234567-0",
                            Direccion = "Av. San Martín 1520",
                            Email = "compras@elnorte.com.ar",
                            Localidad = "San Luis",
                            RazonSocial = "Distribuidora El Norte S.R.L.",
                            Telefono = "266-4123456"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "30-68901234-1",
                            Direccion = "Belgrano 890",
                            Email = "pedidos@lafamilia.com.ar",
                            Localidad = "Villa Mercedes",
                            RazonSocial = "Supermercado La Familia S.A.",
                            Telefono = "266-4234567"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "20-30123456-9",
                            Direccion = "Mitre 345",
                            Localidad = "San Luis",
                            RazonSocial = "Almacenes Pérez Hnos.",
                            Telefono = "266-4345678"
                        },
                        new
                        {
                            Id = 4L,
                            Activo = false,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "27-40234567-2",
                            Direccion = "Colón 1200",
                            Email = "lospinos@gmail.com",
                            Localidad = "Merlo",
                            RazonSocial = "Minimarket Los Pinos",
                            Telefono = "266-4456789"
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_detalles_pedido");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_detalles_pedido_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_detalles_pedido_producto_id");

                    b.ToTable("detalles_pedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cantidad = 5,
                            CreadoEn = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 1L,
                            PrecioUnitario = 2400.00m,
                            ProductoId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Cantidad = 10,
                            CreadoEn = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 1L,
                            PrecioUnitario = 1250.00m,
                            ProductoId = 5L
                        },
                        new
                        {
                            Id = 3L,
                            Cantidad = 3,
                            CreadoEn = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 1L,
                            PrecioUnitario = 3400.00m,
                            ProductoId = 6L
                        },
                        new
                        {
                            Id = 4L,
                            Cantidad = 20,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 2L,
                            PrecioUnitario = 950.00m,
                            ProductoId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Cantidad = 15,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 2L,
                            PrecioUnitario = 1100.00m,
                            ProductoId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            Cantidad = 8,
                            CreadoEn = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 3L,
                            PrecioUnitario = 2400.00m,
                            ProductoId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Cantidad = 6,
                            CreadoEn = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 3L,
                            PrecioUnitario = 3400.00m,
                            ProductoId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            Cantidad = 12,
                            CreadoEn = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 4L,
                            PrecioUnitario = 1250.00m,
                            ProductoId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            Cantidad = 4,
                            CreadoEn = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 5L,
                            PrecioUnitario = 1800.00m,
                            ProductoId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            Cantidad = 8,
                            CreadoEn = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            PedidoId = 5L,
                            PrecioUnitario = 950.00m,
                            ProductoId = 2L
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pedido");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_pedidos_numero");

                    b.ToTable("pedidos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            ClienteId = 1L,
                            CreadoEn = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "Entregado",
                            FechaPedido = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "PED-000001",
                            Observaciones = "Entregar en depósito trasero"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            ClienteId = 2L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "Despachado",
                            FechaPedido = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "PED-000002"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            ClienteId = 1L,
                            CreadoEn = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "EnPreparacion",
                            FechaPedido = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "PED-000003",
                            Observaciones = "Urgente, requiere factura A"
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            ClienteId = 3L,
                            CreadoEn = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "Confirmado",
                            FechaPedido = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "PED-000004"
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            ClienteId = 2L,
                            CreadoEn = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "Pendiente",
                            FechaPedido = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "PED-000005"
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Caja x 12 unidades",
                            Disponible = true,
                            Nombre = "Aceite de Girasol 1.5L",
                            Precio = 2400.00m
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CategoriaId = 2L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Pack x 10 unidades",
                            Disponible = true,
                            Nombre = "Harina 000 1kg",
                            Precio = 950.00m
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Bolsa x 10 unidades",
                            Disponible = false,
                            Nombre = "Arroz Largo Fino 1kg",
                            Precio = 1800.00m
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            CategoriaId = 2L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Caja x 20 paquetes",
                            Disponible = true,
                            Nombre = "Fideos Guiseros 500g",
                            Precio = 1100.00m
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            CategoriaId = 1L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Fardo x 10 unidades",
                            Disponible = true,
                            Nombre = "Azúcar Común 1kg",
                            Precio = 1250.00m
                        },
                        new
                        {
                            Id = 6L,
                            Activo = true,
                            CategoriaId = 3L,
                            CreadoEn = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Pack x 6 unidades",
                            Disponible = true,
                            Nombre = "Yerba Mate 1kg",
                            Precio = 3400.00m
                        });
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("MercuryGo.Api.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_pedido_pedidos_pedido_id");

                    b.HasOne("MercuryGo.Api.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_pedido_productos_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("MercuryGo.Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Producto", b =>
                {
                    b.HasOne("MercuryGo.Api.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MercuryGo.Api.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
